<?php
// Include the TCPDF library
require_once('tcpdf/tcpdf.php'); // Adjust the path as needed

// Start the session
session_start();

// Check if user is logged in
if (!isset($_SESSION['user_email'])) {
    header("Location: index.html");
    exit();
}

// Use the correct session variable for the email
$email = $_SESSION['user_email'];

// Include database connection
include 'connect.php';

// Prepare SQL statements to fetch student details and marks for all terms
$studentQuery = "SELECT * FROM student WHERE email = ?";
$marksQuery = "SELECT * FROM marks WHERE email = ?";

// Prepare and execute the student query
$stmt = $pdo->prepare($studentQuery);
$stmt->bindParam(1, $email);
$stmt->execute();
$studentResult = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Prepare and execute the marks query
$stmtMarks = $pdo->prepare($marksQuery);
$stmtMarks->bindParam(1, $email);
$stmtMarks->execute();
$marksResults = $stmtMarks->fetchAll(PDO::FETCH_ASSOC);

// Function to determine grade based on marks
function getGrade($marks) {
    if ($marks >= 91) return 'A+';
    if ($marks >= 81) return 'A';
    if ($marks >= 71) return 'B';
    if ($marks >= 61) return 'C';
    if ($marks >= 51) return 'D';
    if ($marks >= 36) return 'E';
    return 'F';
}

// Check if student data is available
if (count($studentResult) > 0 && count($marksResults) > 0) {
    $student = $studentResult[0];

    // Prepare data for PDF
    $termsData = [];
    foreach ($marksResults as $marks) {
        $totalMarks = $marks['english'] + $marks['hindi'] + $marks['sst'] + $marks['science'] + $marks['maths'];
        $percentage = ($totalMarks / 500) * 100;

        $termsData[] = [
            'term' => $marks['term'],
            'marks' => [
                'English' => $marks['english'],
                'Hindi' => $marks['hindi'],
                'SST' => $marks['sst'],
                'Science' => $marks['science'],
                'Maths' => $marks['maths'],
            ],
            'grades' => [
                'English' => getGrade($marks['english']),
                'Hindi' => getGrade($marks['hindi']),
                'SST' => getGrade($marks['sst']),
                'Science' => getGrade($marks['science']),
                'Maths' => getGrade($marks['maths']),
            ],
            'total' => $totalMarks,
            'percentage' => round($percentage, 2),
            'remark' => ($percentage < 36) ? 'Fail' : 'Pass',
        ];
    }
} else {
    echo "<div>No student data found.</div>";
    exit();
}

// Create a new PDF document
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('School ABC');
$pdf->SetTitle('Student Marksheet');
$pdf->SetHeaderData('', 0, 'Marksheet', 'Generated by Student Analysis Tool');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Add a page
$pdf->AddPage();

// Set content for PDF
$html = '<h1>Marksheet</h1>';
$html .= '<p><strong>Name:</strong> ' . htmlspecialchars($student['name']) . '</p>';
$html .= '<p><strong>ID:</strong> ' . htmlspecialchars($student['ID']) . '</p>';
$html .= '<p><strong>DOB:</strong> ' . htmlspecialchars($student['dob']) . '</p>';
$html .= '<p><strong>Gender:</strong> ' . htmlspecialchars($student['gender']) . '</p>';
$html .= '<h2>Marks</h2>';

foreach ($termsData as $termData) {
    $html .= '<h3>' . htmlspecialchars($termData['term']) . '</h3>';
    $html .= '<table border="1" cellpadding="5"><tr><th>Subject</th><th>Marks</th><th>Grade</th></tr>';
    foreach ($termData['marks'] as $subject => $marks) {
        $html .= '<tr><td>' . htmlspecialchars($subject) . '</td><td>' . htmlspecialchars($marks) . '</td><td>' . htmlspecialchars($termData['grades'][$subject]) . '</td></tr>';
    }
    $html .= '</table>';
    $html .= '<p><strong>Total:</strong> ' . $termData['total'] . ' out of 500</p>';
    $html .= '<p><strong>Percentage:</strong> ' . $termData['percentage'] . '%</p>';
    $html .= '<p><strong>Remark:</strong> ' . htmlspecialchars($termData['remark']) . '</p>';
}

// Close and output PDF document
$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output('marksheet.pdf', 'D'); // Force download

// After download, redirect to report.php
header("Location: report.php");
exit();
?>
